### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by shesek**
Usage:

```bash
$ git clone https://github.com/KanoczTomas/01Cnode && cd 01Cnode
$ docker build -t 01c .

$ wget https://raw.githubusercontent.com/KanoczTomas/01Cnode/master/config/default.yaml
$ edit default.yaml

$ docker run -p 5000:5000 \
      -v `pwd`/default.yaml:/opt/01cnode/config/default.yaml \
      -v `pwd`/server.log:/opt/01cnode/server.log \
      01c
```

### CODE REVIEW

**Comment by shesek** [comment]
Would be great if you could also push the image to Docker Cloud, so that users won't have to build it themselves.

https://docs.docker.com/docker-cloud/builds/push-images/

**Comment by KanoczTomas** [comment]
Hi! Thanks a lot for the Docker file. Could you please document how to enable the vm to communicate to a bitcoin daemon (the bitcoind config has to allow the IP of the vm for RPC, how would one get that IP)? Could you also create a docker_usage.md separate file to document how to run the docker image? 

Thanks!

**Comment by shesek** [comment]
> Could you please document how to enable the vm to communicate to a bitcoin daemon (the bitcoind config has to allow the IP of the vm for RPC, how would one get that IP)? 

Two options:

1. From within the container, use `ip route | grep default | cut -d' ' -f3` to get the IP of the host.

2. Run docker with `--net host`, which will share networking and make the host available as `127.0.0.1` from within the container.

> Could you also create a docker_usage.md separate file to document how to run the docker image?

Will try to do that, but not sure when I'll be able to get around to that.

**Comment by KanoczTomas** [comment]
@shesek any idea how to add the container's IP to bitcoind's `allowip` directive? As I have trouble in my setup, the docker image does not connect to rpc as it is not allowed. I tried googling, but no luck. I will be travelling, will check later, but if you know the answer that would help a lot :)

**Comment by KanoczTomas** [comment]
@shesek ignore, solved. Thanks a lot for the docker PR.

**Pull request merged**
